# Generated by Django 2.2.5 on 2020-02-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_comment_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='role',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
